# Generated by Django 4.0.3 on 2022-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='nick_name'),
        ),
    ]
