# Generated by Django 4.0.3 on 2022-03-28 04:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.RemoveField(
            model_name='needs',
            name='categorys',
        ),
        migrations.AddField(
            model_name='needs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.categories'),
        ),
    ]
