# Generated by Django 4.0.3 on 2022-03-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needs',
            name='main_img',
        ),
    ]
