# Generated by Django 4.0.3 on 2022-03-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needs',
            old_name='script',
            new_name='description',
        ),
    ]
