# Generated by Django 4.0.3 on 2022-03-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_rename_script_needs_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needs',
            name='tags',
        ),
    ]
