# Generated by Django 4.0.3 on 2022-03-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_remove_needs_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category_name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='needs',
            name='category',
        ),
        migrations.AlterField(
            model_name='needs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Categotise',
        ),
        migrations.AddField(
            model_name='category',
            name='Need',
            field=models.ManyToManyField(to='needs.needs'),
        ),
        migrations.AddField(
            model_name='needs',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.category'),
        ),
    ]
