# Generated by Django 4.0.3 on 2022-03-13 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('needs', '0003_category_remove_needs_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needs',
            name='Category',
        ),
        migrations.AddField(
            model_name='needs',
            name='categorys',
            field=models.ManyToManyField(null=True, to='needs.category'),
        ),
        migrations.AddField(
            model_name='needs',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='needs',
            name='like',
            field=models.ManyToManyField(null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='needs',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=300)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='needs.needs')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
