# Generated by Django 4.0.3 on 2022-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_remove_needs_category_needs_categorys_needs_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='categorys',
            field=models.ManyToManyField(to='needs.category'),
        ),
    ]
